baseURL: http://worstwizard.online
languageCode: en-us
title: The Premier Bad Wizard of the Internet
theme: ficturina
copyright: use whatever you want dude just go for it
paginate: 8
summaryLength: 70
author: Ward Alexander
avatar: mage.png
params:
  description: he/him | kubernetes, games, birds, models, licorice, oats |
    interested in distributed systems of all types | The heart is a muscle the
    size of your fist
  enableShareOnFediverse: true
  avatar: /mage.png
  logo: /mage.png
  svgicon: /mage.png
  featured: "true"
  #commento: https://cdn.commento.io/js/commento.js
menu:
  icons:
    - identifier: mastodon
      name: Mastodon
      url: https://dice.camp/@tupperward
      weight: 30
    - identifier: calendar
      name: Sansculottides
      url: https://sansculottid.es
      weight: 20
    - identifier: twitter
      name: BlueSky
      url: https://bsky.app/profile/worstwizard.online
      weight: 40
    - identifier: email
      name: Email
      url: 'mailto:tupperward@worstwizard.online'
      weight: 10

