baseURL: http://worstwizard.online
languageCode: en-us
title: Idiot Wizard of the Internet
theme: ficturina
copyright: use whatever you want dude just go for it
paginate: 8
summaryLength: 70
author: Ward Alexander
avatar: mage.png
params:
  description: kubernetes, games, birds, models, licorice, oats
    interested in distributed systems of all types 
    The heart is a muscle the size of your fist
  enableShareOnFediverse: true
  avatar: /mage.png
  logo: /mage.png
  svgicon: /mage.png
  featured: "true"
  commento: https://commento.worstwizard.online/js/commento.js
menu:
  icons:
    - identifier: kofi
      name: Kofi
      url: https://ko-fi.com/tupperward
      weight: 40
    - identifier: calendar
      name: Sansculottides
      url: https://sansculottid.es
      weight: 20
    - identifier: twitter
      name: BlueSky
      url: https://bsky.app/profile/worstwizard.online
      weight: 30
    - identifier: email
      name: Email
      url: 'mailto:tupperward@worstwizard.online'
      weight: 10

