name: Kubectl Rollout Restart
on:
  workflow_run:
    workflows: [Docker Build and Publish to DigitalOcean CR]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      # Set up the Kubernetes CLI with your DigitalOcean Kubernetes cluster.
      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DO_TOKEN }}
          clusterName: ${{ env.CLUSTER_NAME}}

      # Run any kubectl commands you want!
      - name: Rollout Pods
        run: kubectl rollout restart ${{ env.RESOURCE }} ${{ env.NAMESPACE }} ${{ env.RESOURCE_NAME }} 